<a href="https://colab.research.google.com/github/LAGISHETTYNANDITHA/aiml-2024/blob/main/2203a52097_aiml(part1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**part 1**

In [ ]:
#1,2,3 questions
import numpy as np
list1=[1,2,3]
n1=np.array(list1)
print("list1",list1)
print("n1",n1)
print("type=",type(n1))
print("type=",type(list1))

list1 [1, 2, 3]
n1 [1 2 3]
type= <class 'numpy.ndarray'>
type= <class 'list'>


In [ ]:
# 4th code
import numpy as np
arr1=(5,6,7,8)
arr2=(9,10,11,12)
mul=np.multiply(arr1,arr2)
print(mul)
div=np.divide(arr1,arr2)
print(div)
pow=np.power(arr1,arr2)
print(pow)

[45 60 77 96]
[0.55555556 0.6        0.63636364 0.66666667]
[    1953125    60466176  1977326743 68719476736]


In [ ]:
#5th question
data1 = np.array([2, 4, 6, 8, 10])
data2 =np.array( [1, 2, 3, 4, 5])
print("addition of two array:",data1+data2)

addition of two array: [ 3  6  9 12 15]


In [ ]:
#6th code
list1=[1,2,3,4]
print(np.sin(list1))
print(np.log(list1))
print(np.log2(list1))
print(np.exp(list1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')